server:
  port: 8080  

spring:
  datasource:
    #url: jdbc:h2:mem:student
    url: jdbc:postgresql://ec2-44-198-82-71.compute-1.amazonaws.com:5432/dfju987b6tfb32
    username: kdqiixqvirvdeh
    password: e6d761539cd961d9743eba27f1f06cb703f592954e167d9108ca2c530bf6b594
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: My First App